# Generated by Django 2.1.5 on 2019-03-13 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', max_length=50)),
                ('task_start_time', models.BigIntegerField(default=0)),
                ('task_end_time', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='addtask',
            name='task',
            field=models.ManyToManyField(to='homeApp.Task'),
        ),
        migrations.AddField(
            model_name='addtask',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
