# Generated by Django 2.1.5 on 2019-02-03 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='domainentity_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homeApp.DomainEntity'),
            preserve_default=False,
        ),
    ]
