# Generated by Django 2.1.5 on 2019-02-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_auto_20190203_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', max_length=50)),
                ('task_start_time', models.BigIntegerField(default=0)),
                ('task_end_time', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='serverinfo',
            name='domainentity_ptr',
        ),
        migrations.DeleteModel(
            name='DomainEntity',
        ),
        migrations.DeleteModel(
            name='ServerInfo',
        ),
        migrations.AddField(
            model_name='addtask',
            name='tasks',
            field=models.ManyToManyField(to='homeApp.Task'),
        ),
    ]
