# Generated by Django 2.1.5 on 2019-02-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0003_auto_20190204_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
