# Generated by Django 2.1.5 on 2019-02-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_addtask_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
