# Generated by Django 2.1.5 on 2019-02-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0006_addtask_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtask',
            name='author',
        ),
    ]
