# Generated by Django 2.1.5 on 2019-03-03 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0008_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
